from chartviz_community_core import AnalysisReport


def make_report() -> AnalysisReport:
    return AnalysisReport.model_validate({
        "imageQuality": {"quality": "high", "limitations": [], "confidence": 0.94},
        "marketReading": {
            "trend": "bullish",
            "structure": "transition",
            "confidence": 0.82,
            "evidence": [{
                "claim": "Price is holding above the latest visible swing low.",
                "visualEvidence": "Latest closed 15m candle",
                "confidence": 0.82,
            }],
        },
        "bullishEvidence": ["The latest visible swing low is holding."],
        "bearishEvidence": ["Price remains below nearby resistance."],
        "conflicts": [],
        "dominantBias": "bullish",
        "overallConfidence": 0.8,
        "decision": {
            "direction": "wait",
            "status": "waiting_confirmation",
            "summary": "Wait for a closed breakout confirmation.",
            "primaryRisk": "A rejection can return price to the prior range.",
        },
        "insights": [],
        "keyLevels": [],
        "patterns": [],
        "scenarios": {
            "long": {
                "trigger": "Close above resistance",
                "confirmation": "Retest holds",
                "invalidation": "Close below support",
                "targetLogic": "Prior swing high",
                "mainRisk": "Failed breakout",
            },
            "short": {
                "trigger": "Break below support",
                "confirmation": "Retest fails",
                "invalidation": "Reclaim support",
                "targetLogic": "Range low",
                "mainRisk": "Rapid reclaim",
            },
            "wait": {
                "conditions": "No closed trigger",
                "resolution": "Wait for confirmation",
            },
        },
        "drawings": [],
        "conclusions": [],
        "segments": [],
        "indicatorReadings": [],
        "volumeAnalysis": None,
        "positioningEvidence": [],
        "timeframeAnalyses": [],
        "tradeSignals": [],
        "riskNotice": "Chart research only.",
        "schemaVersion": "1.3",
        "analysisContext": {
            "instrument": "BTCUSDT",
            "venue": "Example",
            "capturedAt": None,
            "timeframes": [{"timeframe": "15m", "role": "setup_and_trigger"}],
            "latestCandleClosed": True,
            "dataSources": ["screenshot"],
            "limitations": [],
        },
        "evidence": [{
            "id": "NE001",
            "claim": "The latest visible swing low is holding.",
            "source": "screenshot",
            "timeframe": "15m",
            "timeAnchor": "latest closed candle",
            "observationClass": "direct",
            "confidence": 0.82,
        }],
        "marketState": {
            "regime": "transition",
            "directionalBias": "bullish",
            "structure": "transition",
            "currentLocation": "Above the latest visible swing low",
            "supportingEvidenceRefs": ["NE001"],
            "opposingEvidenceRefs": [],
            "confidence": 0.82,
        },
        "zones": [{
            "id": "Z01",
            "type": "support",
            "tier": "nearest",
            "status": "holding",
            "band": {
                "lower": 62000,
                "upper": 63000,
                "label": "62,000–63,000",
                "precision": "estimated",
            },
            "timeframe": "15m",
            "score": 3,
            "scoreFactors": ["visible swing low"],
            "evidenceRefs": ["NE001"],
        }],
        "setupEvaluation": {
            "playbook": "none",
            "state": "preparing",
            "direction": None,
            "location": None,
            "premise": None,
            "entry": None,
            "trigger": None,
            "confirmation": None,
            "triggerCandleClosed": None,
            "structuralStop": None,
            "targets": [],
            "effectiveRToT1": None,
            "actionability": "WAIT",
            "vetoes": [],
            "pendingConditions": [],
            "whatChangesDecision": [],
            "evidenceRefs": ["NE001"],
            "opposingEvidenceRefs": [],
        },
    })
