export const en = {
  slogan: 'Instant pattern intelligence – wherever you trade.',
  language: 'Language', close: 'Close', refresh: 'Refresh', settings: 'Settings', analysisSettings: 'Analysis settings', analysisSettingsHelp: 'Review or change the model and connection used for future analyses.', providerSetup: 'Connect your own vision model', providerSetupHelp: 'Choose how ChartViz reads chart screenshots before your first analysis.',
  setupChooseModel: 'Select a vision-capable model.', setupEnterKey: 'Enter your own API key.', setupDirectSend: 'ChartViz sends the captured chart directly to the selected service.',
  model: 'Model', apiKey: 'API key', showApiKey: 'Show API key', hideApiKey: 'Hide API key', customModel: 'Custom model', customModelId: 'Custom model ID', customModelHelp: 'Use a custom OpenRouter model ID.', otherModels: 'Other',
  useOpenRouter: 'Use OpenRouter', openRouterHelp: 'One API key for models from different providers.', openRouterRequired: 'Required for this model.',
  multimodalWarning: 'Custom models must support image input. Text-only models cannot analyze chart screenshots.', sessionKeyPrivacy: 'Your key stays in extension session storage. Screenshots go directly to the selected service.',
  connectionCost: 'Testing the connection sends a provider request and may incur a small charge.', testConnection: 'Test connection', testingConnection: 'Testing…', connectionOk: 'Connection successful.', saveContinue: 'Save and continue', saveSettings: 'Save settings',
  invalid_config: 'Check the API key and model.', invalid_api_key: 'The API key is invalid.', model_not_found: 'The selected model was not found.', model_not_multimodal: 'The selected model does not support image input.', insufficient_balance: 'The provider account has insufficient balance.', rate_limited: 'The provider rate limit was reached.', invalid_image: 'The chart image could not be read.', network_timeout: 'The provider request timed out.', invalid_response: 'The model response did not match the required report format. Try again or choose another model.', cancelled: 'Analysis cancelled.', unknownError: 'Something went wrong.',
  detectedChart: 'Detected chart', detectedChartHelp: 'Review the current chart before ChartViz captures and analyzes it.', waitingForChart: 'Waiting for chart…', captureAnalyze: 'Capture and analyze', capturingChart: 'Capturing chart…', refreshChartDetection: 'Refresh chart detection', exchange: 'Exchange', notDetected: 'Not detected', chartUnavailable: 'Chart unavailable', chartDetectionError: 'Unable to detect the active chart.', chartCaptureError: 'Unable to capture the active chart.', unsupportedPage: 'This page is not supported', unsupportedChartHelp: 'Upload a chart screenshot here, or open a chart on one of the supported sites below.', supportedSites: 'Supported sites', uploadScreenshot: 'Upload a chart screenshot', uploadingScreenshot: 'Preparing screenshot…', uploadError: 'Unable to read this screenshot.',
  preview: 'Screenshot preview', previewAlt: 'Chart ready for analysis', changeImage: 'Capture again', analyze: 'Analyze screenshot', cancel: 'Cancel analysis', backPreview: 'Back to preview', retry: 'Try again', viewDiagnostics: 'View diagnostics', hideDiagnostics: 'Hide diagnostics', copyDiagnostics: 'Copy diagnostics', diagnosticsCopied: 'Diagnostics copied', diagnosticHelp: 'Share this safe diagnostic when the problem happens again. It excludes your API key, screenshot, prompt, and full model response.', requestId: 'Request ID', failureStage: 'Failure stage', duration: 'Duration', issues: 'Validation issues',
  reading_chart: 'Reading chart', organizing_evidence: 'Reviewing evidence', preparing_result: 'Preparing result',
  original: 'Original screenshot', zoom: 'Zoom', download: 'Download image', copyReport: 'Copy report', copied: 'Copied',
  chart: 'Chart', instrument: 'Instrument', timeframe: 'Timeframe', limitations: 'Limitations', marketView: 'Market view', currentView: 'Current view', marketExplanation: 'Market explanation', tradePlan: 'Trade plan', priceAction: 'Price action', priceVolume: 'Price & volume', technicalIndicators: 'Technical indicators', primaryRisk: 'Primary risk', trend: 'Trend', structure: 'Structure', bias: 'Bias', phase: 'Phase', strength: 'Strength', evidence: 'Evidence', observation: 'Observation', implication: 'Implication', visibleAt: 'Visible at', confidence: 'Confidence', volume: 'Volume', indicators: 'Indicators', supportResistance: 'Support and resistance', levelTier: 'Level', levelStatus: 'Status', reason: 'Reason', scenarios: 'Scenarios', long: 'Long', short: 'Short', wait: 'Wait', condition: 'Condition', entry: 'Entry', stop: 'Stop', targets: 'Targets', patterns: 'Chart patterns', status: 'Status', timeRange: 'Visible range', signals: 'Trade signals', signalType: 'Signal', signalTime: 'Signal time', setupAtSignal: 'Setup at signal', confirmation: 'Confirmation', invalidation: 'Invalidation', direction: 'Direction', riskReward: 'Risk/reward', riskNotice: 'Risk notice', none: 'None',
} as const;

export type TranslationKey = keyof typeof en;
