import type { TranslationKey } from './en';

export const zhCN: Record<TranslationKey, string> = {
  slogan: '智能识图，交易无界。',
  language: '语言', close: '关闭', refresh: '刷新', settings: '设置', backToChart: '返回图表', analysisSettings: '分析设置', analysisSettingsHelp: '查看或修改后续分析所使用的模型和连接。', providerSetup: '连接你自己的视觉模型', providerSetupHelp: '首次分析前，先选择 ChartViz 读取图表截图的方式。',
  setupChooseModel: '选择一个支持图像输入的模型。', setupEnterKey: '输入你自己的 API 密钥。', setupDirectSend: 'ChartViz 会将截图直接发送给所选服务。',
  model: '模型', apiKey: 'API 密钥', showApiKey: '显示 API 密钥', hideApiKey: '隐藏 API 密钥', customModel: '自定义模型', customModelId: '自定义模型 ID', customModelHelp: '使用自定义 OpenRouter 模型 ID。', otherModels: '其他',
  useOpenRouter: '使用 OpenRouter', openRouterHelp: '一个 API 密钥即可使用不同提供商的模型。', openRouterRequired: '此模型需要 OpenRouter。',
  multimodalWarning: '自定义模型必须支持图像输入。纯文本模型无法分析图表截图。', privacyTitle: '隐私与数据', sessionKeyPrivacy: '密钥仅保存在扩展会话中，截图会直接发送给所选服务。',
  analysisRequestNotice: '每次分析会向所选提供商发送 3 次请求；失败后不会自动重试。', connectionCost: '测试连接会向提供商发送 1 次请求，并可能产生少量费用。', testConnection: '测试连接', testingConnection: '测试中…', connectionOk: '连接成功。', saveContinue: '保存并继续', saveSettings: '保存设置',
  invalid_config: '请检查 API 密钥和模型。', invalid_api_key: 'API 密钥无效。', model_not_found: '找不到所选模型。', model_not_multimodal: '所选模型不支持图像输入。', insufficient_balance: '提供商账户余额不足。', rate_limited: '已达到提供商速率限制。', invalid_image: '无法读取图表图片。', network_timeout: '提供商请求超时。', invalid_response: '模型返回内容不符合报告格式，请重试或更换模型。', multi_timeframe_requires_cloud: '多周期分析由 ChartViz Cloud 提供，直连模型暂不支持。', authentication_required: '请先连接 ChartViz Cloud。', invalid_token: 'Cloud 访问令牌无效。', token_revoked: 'Cloud 访问令牌已被撤销。', token_expired: 'Cloud 访问令牌已过期。', insufficient_scope: '此 Cloud 令牌缺少所需权限。', free_trial_exhausted: '免费分析额度已用完。', subscription_required: '需要有效的 ChartViz 套餐才能继续。', subscription_expired: 'ChartViz 套餐已过期。', quota_exhausted: '分析配额已用完。', multi_timeframe_requires_advance: '多周期分析需要 Advance 套餐。', invalid_chart_image: '截图不是可识别的 K 线图。', unsupported_timeframe: '暂不支持该周期。', task_not_found: '找不到该分析任务。', task_failed: '图表分析失败，请重试。', incompatible_api_version: '请更新 ChartViz 以连接当前 Cloud API。', incompatible_report_schema: '请更新 ChartViz 以读取当前 Cloud 报告。', service_unavailable: 'ChartViz Cloud 暂时不可用。', cancelled: '分析已取消。', unknownError: '发生错误。',
  detectedChart: '已检测图表', detectedChartHelp: '确认当前图表信息后，ChartViz 将截取并开始分析。', waitingForChart: '正在等待图表…', captureAnalyze: '截图并分析', capturingChart: '正在截取图表…', refreshChartDetection: '重新检测图表', exchange: '交易所', notDetected: '未识别', chartUnavailable: '当前图表不可用', chartDetectionError: '无法检测当前图表。', chartCaptureError: '无法截取当前图表。',
  screenshotMode: '截图方式', singleTimeframe: '单周期分析', currentChart: '当前图表', multiTimeframe: '多周期分析', contextRole: '背景', setupRole: '结构', triggerRole: '触发', openCloudSettings: '查看 Cloud 设置', multiTimeframeSiteUnsupported: '当前站点不支持多周期截图。', multiTimeframeFlicker: '截图时会切换图表周期，页面可能短暂闪烁。',
  unsupportedSiteTitle: '当前站点暂不支持', unsupportedSiteHelp: '你可以前往 ChartViz 上传清晰的 K 线截图，或打开下方任一已支持的图表站点。', unsupportedUrlTitle: '当前页面不是受支持的图表页面', unsupportedUrlHelp: '请打开包含 K 线、价格、成交量和可见周期的图表页面。', uploadOnChartViz: '前往 ChartViz 上传截图', uploadOnCurrentChartViz: '使用当前页面的截图上传区域', openSiteBtcChart: '打开 {site} 的 BTC 图表', supportedSites: '支持的站点',
  analysisMode: '分析模式', chartVizCloud: 'ChartViz Cloud', directModel: '直连模型', cloudSetupTitle: '托管式图表分析', cloudSetupHelp: '使用 ChartViz Cloud，无需在插件中管理模型密钥。', cloudMultiTimeframe: '当前 Cloud 版本每次分析支持一个周期。', cloudToken: 'Cloud 访问令牌', cloudTokenHelp: '请先在 ChartViz 网站设置中创建可撤销令牌，然后粘贴到这里。', cloudConnect: '连接 Cloud', cloudConnecting: '正在连接…', cloudTokenWebsite: '在 ChartViz 创建或撤销令牌', cloudConnected: 'Cloud 已连接', cloudDisconnect: '断开连接', cloudDisconnectHelp: '断开只会删除当前插件中的令牌；如需使其他安装失效，请前往网站撤销。', cloudPlan: '套餐', cloudPlanExpires: '套餐到期', cloudQuota: '配额', cloudUnlimited: '不限量', cloudModel: '分析模型', cloudMultiEnabled: '已支持多周期', cloudMultiDisabled: '仅支持单周期', cloudC1Notice: 'Cloud 分析已可用。', cloudErrorAuthentication: '请输入 ChartViz Cloud 访问令牌。', cloudErrorInvalid: 'Cloud 访问令牌无效。', cloudErrorRevoked: 'Cloud 访问令牌已被撤销。', cloudErrorExpired: 'Cloud 访问令牌已过期。', cloudErrorScope: '此令牌无权读取账户信息。', cloudErrorService: 'ChartViz Cloud 暂时不可用，请稍后重试。',
  preview: '截图预览', previewAlt: '图表已可分析', changeImage: '重新截图', analyze: '分析截图', cancel: '取消分析', backPreview: '返回预览', retry: '重试', viewPlans: '查看套餐', viewDiagnostics: '查看诊断信息', hideDiagnostics: '收起诊断信息', copyDiagnostics: '复制诊断信息', downloadDiagnostics: '下载诊断 JSON', completeDiagnostic: '完整诊断 JSON', diagnosticsCopied: '复制成功', diagnosticsCopyFailed: '复制失败，请改用下载诊断 JSON。', diagnosticHelp: '失败快照只保存在当前插件中，包含用于调试的提示词和模型结构化输出，但不包含 API 密钥和截图图片数据。', diagnosticSource: '诊断来源', pipelineVersion: '分析管线版本', diagnosticProvider: '模型服务', diagnosticModel: '模型', requestId: '请求 ID', occurredAt: '发生时间', failureStage: '失败阶段', httpStatus: 'HTTP 状态', duration: '耗时', issues: '校验问题',
  preparing: '正在准备分析…', reading_chart: '正在解读图表…', reviewing_clues: '发现了一些值得关注的市场线索…', checking_signals: '正在核对关键位置和交易条件…', preparing_result: '正在整理分析结果…',
  original: '原始截图', zoom: '放大', download: '下载图片', copyReport: '复制报告', copied: '已复制',
  chart: '图表', instrument: '交易品种', timeframe: '周期', limitations: '局限', marketView: '市场观点', currentView: '当前观点', marketExplanation: '行情解读', tradePlan: '交易方案', priceAction: '价格变化', priceVolume: '量价解读', technicalIndicators: '技术指标解读', primaryRisk: '主要风险', trend: '当前走势', structure: '市场结构', bias: '方向', phase: '阶段', strength: '强度', evidence: '证据', observation: '观察', implication: '含义', visibleAt: '图上位置', confidence: '置信度', volume: '成交量', indicators: '技术指标', supportResistance: '支撑位与阻力位', levelTier: '级别', levelStatus: '状态', reason: '理由', scenarios: '情景计划', long: '做多', short: '做空', wait: '等待', condition: '条件', entry: '入场', stop: '止损', targets: '目标', patterns: '图表形态', status: '状态', timeRange: '可见范围', signals: '交易信号解读', signalType: '信号类型', signalTime: '信号时间', setupAtSignal: '当时的信号依据', confirmation: '确认条件', invalidation: '失效条件', direction: '方向', riskReward: '预计盈亏比', riskNotice: '风险提示', none: '无',
};
