/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/extension/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExtensionAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extension/analysis-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createExtensionAnalysisTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extension/analysis-tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExtensionAnalysisTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extension/analysis-tasks/{task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelExtensionAnalysisTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extension/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExtensionCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ExtensionAccount */
        ExtensionAccount: {
            /**
             * Currentperiodend
             * @default null
             */
            currentPeriodEnd: string | null;
            /** Emailmasked */
            emailMasked: string;
            entitlements: components["schemas"]["ExtensionEntitlements"];
            /**
             * Plan
             * @enum {string}
             */
            plan: "free" | "pro" | "advance";
            quota: components["schemas"]["ExtensionQuota"];
            selectedModel: components["schemas"]["ExtensionSelectedModel"];
        };
        /** ExtensionAnalysisCreateMetadata */
        ExtensionAnalysisCreateMetadata: {
            /** Captures */
            captures: components["schemas"]["ExtensionCaptureMetadata"][];
            /**
             * Outputlanguage
             * @enum {string}
             */
            outputLanguage: "en" | "zh-CN";
        };
        /** ExtensionAnalysisTask */
        ExtensionAnalysisTask: {
            /** @default null */
            error: components["schemas"]["ExtensionApiError"] | null;
            /** Progressevents */
            progressEvents?: components["schemas"]["ExtensionProgressEvent"][];
            /** @default null */
            report: components["schemas"]["ExtensionReport"] | null;
            /** Requestid */
            requestId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "cancel_requested" | "cancelled" | "completed" | "failed";
        };
        /** ExtensionApiError */
        ExtensionApiError: {
            /**
             * Code
             * @enum {string}
             */
            code: "authentication_required" | "invalid_token" | "token_revoked" | "token_expired" | "insufficient_scope" | "free_trial_exhausted" | "subscription_required" | "subscription_expired" | "quota_exhausted" | "multi_timeframe_requires_advance" | "invalid_image" | "invalid_chart_image" | "unsupported_timeframe" | "task_not_found" | "task_failed" | "task_cancelled" | "incompatible_api_version" | "incompatible_report_schema" | "service_unavailable";
            /** Params */
            params?: {
                [key: string]: string | number | boolean | null;
            };
            /**
             * Pricingurl
             * @default null
             */
            pricingUrl: string | null;
        };
        /** ExtensionCapabilities */
        ExtensionCapabilities: {
            /**
             * Apiversion
             * @default 1
             * @constant
             */
            apiVersion: "1";
            /**
             * Edition
             * @default cloud
             * @constant
             */
            edition: "cloud";
            features: components["schemas"]["ExtensionCapabilityFeatures"];
            limits: components["schemas"]["ExtensionCapabilityLimits"];
            /**
             * Reportschemaversion
             * @default extension-report-1.0
             * @constant
             */
            reportSchemaVersion: "extension-report-1.0";
        };
        /** ExtensionCapabilityFeatures */
        ExtensionCapabilityFeatures: {
            /** Advancedannotations */
            advancedAnnotations: boolean;
            /** Cloudmanagedmodels */
            cloudManagedModels: boolean;
            /** Multitimeframe */
            multiTimeframe: boolean;
            /** Taskcancellation */
            taskCancellation: boolean;
            /** Taskresume */
            taskResume: boolean;
        };
        /** ExtensionCapabilityLimits */
        ExtensionCapabilityLimits: {
            /** Maximages */
            maxImages: number;
            /** Maxtimeframes */
            maxTimeframes: number;
        };
        /** ExtensionCaptureMetadata */
        ExtensionCaptureMetadata: {
            /** Captureid */
            captureId: string;
            /** Height */
            height: number;
            /**
             * Instrument
             * @default null
             */
            instrument: string | null;
            /**
             * Role
             * @default null
             */
            role: ("context" | "setup" | "trigger") | null;
            /**
             * Site
             * @default null
             */
            site: string | null;
            /** Timeframe */
            timeframe: string;
            /** Width */
            width: number;
        };
        /** ExtensionConclusion */
        ExtensionConclusion: {
            /** Confidence */
            confidence: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "long" | "short" | "sideways";
            /** Primaryrisk */
            primaryRisk: string;
            /**
             * Strength
             * @enum {string}
             */
            strength: "strong" | "moderate" | "weak" | "unclear";
            /**
             * Structure
             * @enum {string}
             */
            structure: "hh-hl" | "lh-ll" | "range" | "transition" | "unclear";
            /** Summary */
            summary: string;
            /**
             * Trend
             * @enum {string}
             */
            trend: "bullish" | "bearish" | "sideways" | "unclear";
        };
        /** ExtensionDrawing */
        ExtensionDrawing: {
            /** Captureid */
            captureId: string;
            /** Id */
            id: string;
            /**
             * Layer
             * @enum {string}
             */
            layer: "levels" | "pattern" | "signal";
            /** Points */
            points: components["schemas"]["ExtensionDrawingPoint"][];
            /** Refid */
            refId: string;
            /**
             * Tool
             * @enum {string}
             */
            tool: "horizontal_line" | "zone" | "trend_line" | "channel" | "range" | "entry_arrow" | "stop_line" | "target_line" | "marker";
        };
        /** ExtensionDrawingPoint */
        ExtensionDrawingPoint: {
            /**
             * Pricelabel
             * @default null
             */
            priceLabel: string | null;
            /**
             * Timeanchor
             * @default null
             */
            timeAnchor: string | null;
            /**
             * Xratio
             * @default null
             */
            xRatio: number | null;
            /** Yratio */
            yRatio: number;
        };
        /** ExtensionEntitlements */
        ExtensionEntitlements: {
            /** Maxcaptures */
            maxCaptures: number;
            /** Multitimeframe */
            multiTimeframe: boolean;
        };
        /** ExtensionEvidenceExplanation */
        ExtensionEvidenceExplanation: {
            /** Evidence */
            evidence: string[];
            /** Summary */
            summary: string;
            /** Timeanchor */
            timeAnchor: string;
        };
        /** ExtensionIndicatorExplanation */
        ExtensionIndicatorExplanation: {
            /** Id */
            id: string;
            /** Implication */
            implication: string;
            /**
             * Name
             * @enum {string}
             */
            name: "RSI" | "MACD" | "OTHER";
            /** State */
            state: string;
            /** Timeanchor */
            timeAnchor: string;
        };
        /** ExtensionLevel */
        ExtensionLevel: {
            /** Captureid */
            captureId: string;
            /** Confidence */
            confidence: number;
            /** Id */
            id: string;
            /** Pricelabel */
            priceLabel: string;
            /** Reason */
            reason: string;
            /**
             * Status
             * @enum {string}
             */
            status: "holding" | "testing" | "broken" | "flip_candidate";
            /**
             * Tier
             * @enum {string}
             */
            tier: "nearest" | "secondary" | "major";
            /** Timeanchor */
            timeAnchor: string;
            /**
             * Type
             * @enum {string}
             */
            type: "support" | "resistance";
            /**
             * Yratio
             * @default null
             */
            yRatio: number | null;
        };
        /** ExtensionMarketExplanation */
        ExtensionMarketExplanation: {
            /** Indicators */
            indicators?: components["schemas"]["ExtensionIndicatorExplanation"][];
            priceAction: components["schemas"]["ExtensionEvidenceExplanation"];
            /** @default null */
            volume: components["schemas"]["ExtensionVolumeExplanation"] | null;
        };
        /** ExtensionPattern */
        ExtensionPattern: {
            /**
             * Bias
             * @enum {string}
             */
            bias: "bullish" | "bearish" | "neutral";
            /** Captureid */
            captureId: string;
            /** Confidence */
            confidence: number;
            /** Confirmation */
            confirmation: string;
            /** Evidence */
            evidence: string;
            /** Id */
            id: string;
            /** Invalidation */
            invalidation: string;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "forming" | "confirmed" | "invalidated";
            /** Timerange */
            timeRange: string;
        };
        /** ExtensionProgressEvent */
        ExtensionProgressEvent: {
            /**
             * Code
             * @enum {string}
             */
            code: "preparing" | "reading_chart" | "reviewing_clues" | "checking_signals" | "preparing_result";
            /** Createdat */
            createdAt: string;
        };
        /** ExtensionQuota */
        ExtensionQuota: {
            /**
             * Limit
             * @default null
             */
            limit: number | null;
            /**
             * Remaining
             * @default null
             */
            remaining: number | null;
            /** Unlimited */
            unlimited: boolean;
            /** Used */
            used: number;
        };
        /** ExtensionReport */
        ExtensionReport: {
            conclusion: components["schemas"]["ExtensionConclusion"];
            context: components["schemas"]["ExtensionReportContext"];
            /** Drawings */
            drawings?: components["schemas"]["ExtensionDrawing"][];
            /** Levels */
            levels?: components["schemas"]["ExtensionLevel"][];
            marketExplanation: components["schemas"]["ExtensionMarketExplanation"];
            /** Patterns */
            patterns?: components["schemas"]["ExtensionPattern"][];
            /** Risknotice */
            riskNotice: string;
            /**
             * Schemaversion
             * @default extension-report-1.0
             * @constant
             */
            schemaVersion: "extension-report-1.0";
            /** Timeframeviews */
            timeframeViews: components["schemas"]["ExtensionTimeframeView"][];
            tradePlan: components["schemas"]["ExtensionTradePlan"];
            /** Tradesignals */
            tradeSignals?: components["schemas"]["ExtensionTradeSignal"][];
        };
        /** ExtensionReportContext */
        ExtensionReportContext: {
            /** Captures */
            captures: components["schemas"]["ExtensionCaptureMetadata"][];
            /**
             * Instrument
             * @default null
             */
            instrument: string | null;
            /**
             * Outputlanguage
             * @enum {string}
             */
            outputLanguage: "en" | "zh-CN";
            /**
             * Venue
             * @default null
             */
            venue: string | null;
        };
        /** ExtensionScenario */
        ExtensionScenario: {
            /** Condition */
            condition: string;
            /** Entry */
            entry: string;
            /** Reason */
            reason: string;
            /** Stop */
            stop: string;
            /** Targets */
            targets: string[];
        };
        /** ExtensionSelectedModel */
        ExtensionSelectedModel: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Quotacost */
            quotaCost: number;
        };
        /** ExtensionSignalPoint */
        ExtensionSignalPoint: {
            /** Pricelabel */
            priceLabel: string;
            /**
             * Xratio
             * @default null
             */
            xRatio: number | null;
            /** Yratio */
            yRatio: number;
        };
        /** ExtensionTimeframeView */
        ExtensionTimeframeView: {
            /** Captureid */
            captureId: string;
            /** Conclusion */
            conclusion: string;
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence: string[];
            /**
             * Role
             * @default null
             */
            role: ("context" | "setup" | "trigger") | null;
            /**
             * Structure
             * @enum {string}
             */
            structure: "hh-hl" | "lh-ll" | "range" | "transition" | "unclear";
            /** Timeframe */
            timeframe: string;
            /**
             * Trend
             * @enum {string}
             */
            trend: "bullish" | "bearish" | "sideways" | "unclear";
        };
        /** ExtensionTradePlan */
        ExtensionTradePlan: {
            long: components["schemas"]["ExtensionScenario"];
            short: components["schemas"]["ExtensionScenario"];
            /** Summary */
            summary: string;
            wait: components["schemas"]["ExtensionWaitScenario"];
        };
        /** ExtensionTradeSignal */
        ExtensionTradeSignal: {
            /** Captureid */
            captureId: string;
            /** Confidence */
            confidence: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "long" | "short";
            entry: components["schemas"]["ExtensionSignalPoint"];
            /** Evidenceatsignal */
            evidenceAtSignal: string[];
            /** Id */
            id: string;
            /** Invalidation */
            invalidation: string;
            /**
             * Riskreward
             * @default null
             */
            riskReward: string | null;
            /** Signaltime */
            signalTime: string;
            /** Signaltype */
            signalType: string;
            stopLoss: components["schemas"]["ExtensionSignalPoint"];
            /** Takeprofits */
            takeProfits: components["schemas"]["ExtensionSignalPoint"][];
            /** Thesisatsignal */
            thesisAtSignal: string;
        };
        /** ExtensionVolumeExplanation */
        ExtensionVolumeExplanation: {
            /** Implication */
            implication: string;
            /** Summary */
            summary: string;
            /** Timeanchor */
            timeAnchor: string;
        };
        /** ExtensionWaitScenario */
        ExtensionWaitScenario: {
            /** Condition */
            condition: string;
            /** Reason */
            reason: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getExtensionAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionAccount"];
                };
            };
            /** @description Request failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionApiError"];
                };
            };
            /** @description Request failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionApiError"];
                };
            };
        };
    };
    createExtensionAnalysisTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    images: string[];
                    metadata: components["schemas"]["ExtensionAnalysisCreateMetadata"];
                };
            };
        };
        responses: {
            /** @description Task accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionAnalysisTask"];
                };
            };
            /** @description Request failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionApiError"];
                };
            };
            /** @description Request failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionApiError"];
                };
            };
            /** @description Request failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionApiError"];
                };
            };
            /** @description Request failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionApiError"];
                };
            };
        };
    };
    getExtensionAnalysisTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionAnalysisTask"];
                };
            };
            /** @description Request failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionApiError"];
                };
            };
            /** @description Request failed */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionApiError"];
                };
            };
        };
    };
    cancelExtensionAnalysisTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionAnalysisTask"];
                };
            };
            /** @description Request failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionApiError"];
                };
            };
            /** @description Request failed */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionApiError"];
                };
            };
            /** @description Request failed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionApiError"];
                };
            };
        };
    };
    getExtensionCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionCapabilities"];
                };
            };
        };
    };
}
